accept:""
accessKey:""
align:""
alt:""
assignedSlot:null
attributes:NamedNodeMap
autocapitalize:"sentences"
autocomplete:"off"
autofocus:false
baseURI:"http://localhost:8069/nf/index.jsp"
checked:false
childElementCount:0
childNodes:NodeList[0]
children:HTMLCollection[0]
classList:DOMTokenList[1]
className:"ui-autocomplete-input"
clientHeight:21
clientLeft:2
clientTop:2
clientWidth:194
contentEditable:"inherit"
dataset:DOMStringMap
defaultChecked:false
defaultValue:""
dir:""
dirName:""
disabled:false
draggable:false
files:null
firstChild:null
firstElementChild:null
form:null
formAction:"http://localhost:8069/nf/index.jsp"
formEnctype:""
formMethod:""
formNoValidate:false
formTarget:""
height:0
hidden:false
id:"tags"
incremental:false
indeterminate:false
innerHTML:""
innerText:""
isConnected:true
isContentEditable:false
jQuery183026919418635922976:1
labels:NodeList[1]
lang:""
lastChild:null
lastElementChild:null
list:null
localName:"input"
max:""
maxLength:-1
min:""
minLength:-1
multiple:false
name:""
namespaceURI:"http://www.w3.org/1999/xhtml"
nextElementSibling:null
nextSibling:text
nodeName:"INPUT"
nodeType:1
nodeValue:null
offsetHeight:24
offsetLeft:61
offsetParent:body
offsetTop:8
offsetWidth:198
onabort:null
onbeforecopy:null
onbeforecut:null
onbeforepaste:null
onblur:null
oncancel:null
oncanplay:null
oncanplaythrough:null
onchange:null
onclick:null
onclose:null
oncontextmenu:null
oncopy:null
oncuechange:null
oncut:null
ondblclick:null
ondrag:null
ondragend:null
ondragenter:null
ondragleave:null
ondragover:null
ondragstart:null
ondrop:null
ondurationchange:null
onemptied:null
onended:null
onerror:null
onfocus:null
oninput:null
oninvalid:null
onkeydown:null
onkeypress:null
onkeyup:null
onload:null
onloadeddata:null
onloadedmetadata:null
onloadstart:null
onmousedown:null
onmouseenter:null
onmouseleave:null
onmousemove:null
onmouseout:null
onmouseover:null
onmouseup:null
onmousewheel:null
onpaste:null
onpause:null
onplay:null
onplaying:null
onprogress:null
onratechange:null
onreset:null
onresize:null
onscroll:null
onsearch:null
onseeked:null
onseeking:null
onselect:null
onselectstart:null
onshow:null
onstalled:null
onsubmit:null
onsuspend:null
ontimeupdate:null
ontoggle:null
onvolumechange:null
onwaiting:null
onwebkitfullscreenchange:null
onwebkitfullscreenerror:null
onwheel:null
outerHTML:"<input id="tags" class="ui-autocomplete-input" autocomplete="off">"
outerText:""
ownerDocument:document
parentElement:div.ui-widget
parentNode:div.ui-widget
pattern:""
placeholder:""
prefix:null
previousElementSibling:label
previousSibling:text
readOnly:false
required:false
scrollHeight:21
scrollLeft:0
scrollTop:0
scrollWidth:194
selectionDirection:"forward"
selectionEnd:1
selectionStart:1
shadowRoot:null
size:20
slot:""
spellcheck:true
src:""
step:""
style:CSSStyleDeclaration
tabIndex:0
tagName:"INPUT"
textContent:""
title:""
translate:true
type:"text"
useMap:""
validationMessage:""
validity:ValidityState
value:"a"
valueAsDate:null
valueAsNumber:NaN
webkitEntries:Array[0]
webkitdirectory:false
webkitdropzone:""
width:0
willValidate:true
__proto__:HTMLInputElement
