altKey:false
attrChange:undefined
attrName:undefined
bubbles:true
cancelable:true
char:undefined
charCode:0
ctrlKey:false
currentTarget:input#tags.ui-autocomplete-input
data:undefined
delegateTarget:input#tags.ui-autocomplete-input
eventPhase:2
handleObj:Object
isDefaultPrevented:returnTrue()
jQuery18305827023929120474:true
key:"Enter"
keyCode:13
metaKey:false
originalEvent:KeyboardEvent
relatedNode:undefined
relatedTarget:undefined
shiftKey:false
srcElement:input#tags.ui-autocomplete-input
target:input#tags.ui-autocomplete-input
timeStamp:8937.210000000001
type:"keydown"
view:Window
which:13
__proto__:Object
